# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/jenkinsxio/jx-slack
  tag: 0.0.43
  pullPolicy: IfNotPresent

podAnnotations: {
  myannotation: abcd
}

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi

gitSecretName: tekton-git

terminationGracePeriodSeconds: 10

jxRequirements:
  cluster:
    gitKind: github
    gitServer: https://github.com

role:
  rules:
  - apiGroups:
    - jenkins.io
    resources:
    - pipelineactivities
    verbs:
    - watch
    - update
    - list
  - apiGroups:
    - jenkins.io
    resources:
    - environments
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - secrets
    - configmaps
    - namespaces
    - serviceaccounts
    verbs:
    - get
    - list
  - apiGroups:
    - extensions
    - "networking.k8s.io"
    resources:
    - ingresses
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - ""
    resources:
    - configmaps
    resourceNames:
    - "plugins"
    verbs:
    - watch
    - get
    - update
