apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: slackbots.slack.app.jenkins-x-labs.com
spec:
  group: slack.app.jenkins-x-labs.com
  names:
    kind: SlackBot
    listKind: SlackBotList
    plural: slackbots
    shortNames:
      - app
    singular: slackbot
  scope: Namespaced
  validation: {}
  additionalPrinterColumns:
  - name: Channel
    type: string
    description: The channel the bot will talk to
    JSONPath: .spec.channel
  - name: Namespace
    type: string
    description: The namespace the bot will watch
    JSONPath: .spec.namespace
  version: v1
