# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: jenkinsxio/slack
  tag: dev
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi

gitSecretName: tekton-git

terminationGracePeriodSeconds: 10

jxRequirements:
  cluster:
    gitKind: github
    gitServer: https://github.com

role:
  rules:
  - apiGroups:
    - jenkins.io
    resources:
    - pipelineactivities
    verbs:
    - watch
    - update
    - list
  - apiGroups:
    - jenkins.io
    resources:
    - environments
    verbs:
    - get
    - list
  - apiGroups:
    - jenkins.io
    resources:
    - users
    verbs:
    - list
    - create
    - update
  - apiGroups:
    - ""
    resources:
    - secrets
    - configmaps
    - namespaces
    - serviceaccounts
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - configmaps
    resourceNames:
    - "plugins"
    verbs:
    - watch
    - get
    - update
  - apiGroups:
    - slack.app.jenkins-x.io
    resources:
    - slackbots
    verbs:
    - list
    - watch
  - apiGroups:
    - vault.banzaicloud.com
    resources:
    - vaults
    verbs:
    - list
    - get
