# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: jenkinsxio/slack
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: slack
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

names:
  tokenSecret: slack-token
  usersSecret: slack-users
  config: slack-config

hmacToken:
  name: hmac-token

googleSecretsManager: false

role:
  rules:
    - apiGroups:
        - jenkins.io
      resources:
        - pipelineactivities
      verbs:
        - watch
        - update
        - list
    - apiGroups:
        - jenkins.io
      resources:
        - environments
      verbs:
        - get
        - list
    - apiGroups:
        - jenkins.io
      resources:
        - users
      verbs:
        - list
        - create
        - update
    - apiGroups:
        - ""
      resources:
        - secrets
        - configmaps
        - namespaces
        - serviceaccounts
      verbs:
        - get
        - list
    - apiGroups:
        - ""
      resources:
        - configmaps
      resourceNames:
        - "plugins"
      verbs:
        - watch
        - get
        - update
    - apiGroups:
        - apps
      resources:
        - deployments
      verbs:
        - get
    - apiGroups:
        - slack.app.jenkins-x.io
      resources:
        - slackbots
      verbs:
        - list
        - watch
    - apiGroups:
        - vault.banzaicloud.com
      resources:
        - vaults
      verbs:
        - list
        - get
