apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: jx-slack
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jx-slack
  template:
    metadata:
      labels:
        app: jx-slack
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: slack
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - "/jx-slack"
        args:
        - run
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        env:
        - name: GIT_KIND
          value: "{{ .Values.jxRequirements.cluster.gitKind }}"
        - name: GIT_SERVER
          value: "{{ .Values.jxRequirements.cluster.gitServer }}"
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Values.gitSecretName }}
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: jx-slack
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ template "name" . }}
