apiVersion: v1
kind: Secret
metadata:
  name: slack-users
  {{- if .Values.googleSecretsManager }}
  annotations:
    jenkins-x.io/gsm-kubernetes-secret-key: mapping.txt
    jenkins-x.io/gsm-secret-id: slack-users
  {{- end }}
type: Opaque